/** Code auto-generated by cOde 1.0.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[18];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define tau_mRNA parms[0] 
 #define tps_repr parms[1] 
 #define KM parms[2] 
 #define n_Hill parms[3] 
 #define tps_active parms[4] 
 #define tau_mRNA_GFP parms[5] 
 #define eff parms[6] 
 #define tau_prot parms[7] 
 #define eff_GFP parms[8] 
 #define tau_prot_GFP parms[9] 
 #define y0_0 parms[10] 
 #define y1_0 parms[11] 
 #define y2_0 parms[12] 
 #define y3_0 parms[13] 
 #define y4_0 parms[14] 
 #define y5_0 parms[15] 
 #define y6_0 parms[16] 
 #define y7_0 parms[17] 
#define tmin range[0]
#define tmax range[1]


void odemodel_Elowitz_Nature2000_initmod(void (* odeparms)(int *, double *)) {
	 int N=18;
	 odeparms(&N, parms);
}

void odemodel_Elowitz_Nature2000_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_Elowitz_Nature2000_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*((y[0]*log(2.0)/tau_mRNA))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[6],n_Hill)))));
 	 ydot[1] = -1.0*((y[1]*log(2.0)/tau_mRNA))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))));
 	 ydot[2] = -1.0*((y[2]*log(2.0)/tau_mRNA))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[5],n_Hill)))));
 	 ydot[3] = -1.0*((y[3]*log(2.0)/tau_mRNA_GFP));
 	 ydot[4] = 1.0*((y[0]*eff/tau_mRNA))-1.0*((y[4]*log(2.0)/tau_prot));
 	 ydot[5] = 1.0*((y[1]*eff/tau_mRNA))-1.0*((y[5]*log(2.0)/tau_prot));
 	 ydot[6] = 1.0*((y[2]*eff/tau_mRNA))-1.0*((y[6]*log(2.0)/tau_prot));
 	 ydot[7] = 1.0*((y[3]*eff_GFP/tau_mRNA_GFP))-1.0*((y[7]*log(2.0)/tau_prot_GFP))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))));

}

