/** Code auto-generated by cOde 1.0.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[116];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define tau_mRNA parms[0] 
 #define tps_repr parms[1] 
 #define KM parms[2] 
 #define n_Hill parms[3] 
 #define tps_active parms[4] 
 #define tau_mRNA_GFP parms[5] 
 #define eff parms[6] 
 #define tau_prot parms[7] 
 #define eff_GFP parms[8] 
 #define tau_prot_GFP parms[9] 
 #define y0_0 parms[10] 
 #define y1_0 parms[11] 
 #define y2_0 parms[12] 
 #define y3_0 parms[13] 
 #define y4_0 parms[14] 
 #define y5_0 parms[15] 
 #define y6_0 parms[16] 
 #define y7_0 parms[17] 
 #define y8_0 parms[18] 
 #define y9_0 parms[19] 
 #define y10_0 parms[20] 
 #define y11_0 parms[21] 
 #define y12_0 parms[22] 
 #define y13_0 parms[23] 
 #define y14_0 parms[24] 
 #define y15_0 parms[25] 
 #define y16_0 parms[26] 
 #define y17_0 parms[27] 
 #define y18_0 parms[28] 
 #define y19_0 parms[29] 
 #define y20_0 parms[30] 
 #define y21_0 parms[31] 
 #define y22_0 parms[32] 
 #define y23_0 parms[33] 
 #define y24_0 parms[34] 
 #define y25_0 parms[35] 
 #define y26_0 parms[36] 
 #define y27_0 parms[37] 
 #define y28_0 parms[38] 
 #define y29_0 parms[39] 
 #define y30_0 parms[40] 
 #define y31_0 parms[41] 
 #define y32_0 parms[42] 
 #define y33_0 parms[43] 
 #define y34_0 parms[44] 
 #define y35_0 parms[45] 
 #define y36_0 parms[46] 
 #define y37_0 parms[47] 
 #define y38_0 parms[48] 
 #define y39_0 parms[49] 
 #define y40_0 parms[50] 
 #define y41_0 parms[51] 
 #define y42_0 parms[52] 
 #define y43_0 parms[53] 
 #define y44_0 parms[54] 
 #define y45_0 parms[55] 
 #define y46_0 parms[56] 
 #define y47_0 parms[57] 
 #define y48_0 parms[58] 
 #define y49_0 parms[59] 
 #define y50_0 parms[60] 
 #define y51_0 parms[61] 
 #define y52_0 parms[62] 
 #define y53_0 parms[63] 
 #define y54_0 parms[64] 
 #define y55_0 parms[65] 
 #define y56_0 parms[66] 
 #define y57_0 parms[67] 
 #define y58_0 parms[68] 
 #define y59_0 parms[69] 
 #define y60_0 parms[70] 
 #define y61_0 parms[71] 
 #define y62_0 parms[72] 
 #define y63_0 parms[73] 
 #define y64_0 parms[74] 
 #define y65_0 parms[75] 
 #define y66_0 parms[76] 
 #define y67_0 parms[77] 
 #define y68_0 parms[78] 
 #define y69_0 parms[79] 
 #define y70_0 parms[80] 
 #define y71_0 parms[81] 
 #define y72_0 parms[82] 
 #define y73_0 parms[83] 
 #define y74_0 parms[84] 
 #define y75_0 parms[85] 
 #define y76_0 parms[86] 
 #define y77_0 parms[87] 
 #define y78_0 parms[88] 
 #define y79_0 parms[89] 
 #define y80_0 parms[90] 
 #define y81_0 parms[91] 
 #define y82_0 parms[92] 
 #define y83_0 parms[93] 
 #define y84_0 parms[94] 
 #define y85_0 parms[95] 
 #define y86_0 parms[96] 
 #define y87_0 parms[97] 
 #define y88_0 parms[98] 
 #define y89_0 parms[99] 
 #define y90_0 parms[100] 
 #define y91_0 parms[101] 
 #define y92_0 parms[102] 
 #define y93_0 parms[103] 
 #define y94_0 parms[104] 
 #define y95_0 parms[105] 
 #define y96_0 parms[106] 
 #define y97_0 parms[107] 
 #define y98_0 parms[108] 
 #define y99_0 parms[109] 
 #define y100_0 parms[110] 
 #define y101_0 parms[111] 
 #define y102_0 parms[112] 
 #define y103_0 parms[113] 
 #define y104_0 parms[114] 
 #define y105_0 parms[115] 
#define tmin range[0]
#define tmax range[1]


void odemodel_Elowitz_Nature2000_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=116;
	 odeparms(&N, parms);
}

void odemodel_Elowitz_Nature2000_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_Elowitz_Nature2000_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*((y[0]*log(2.0)/tau_mRNA))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[6],n_Hill)))));
 	 ydot[1] = -1.0*((y[1]*log(2.0)/tau_mRNA))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))));
 	 ydot[2] = -1.0*((y[2]*log(2.0)/tau_mRNA))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[5],n_Hill)))));
 	 ydot[3] = -1.0*((y[3]*log(2.0)/tau_mRNA_GFP));
 	 ydot[4] = 1.0*((y[0]*eff/tau_mRNA))-1.0*((y[4]*log(2.0)/tau_prot));
 	 ydot[5] = 1.0*((y[1]*eff/tau_mRNA))-1.0*((y[5]*log(2.0)/tau_prot));
 	 ydot[6] = 1.0*((y[2]*eff/tau_mRNA))-1.0*((y[6]*log(2.0)/tau_prot));
 	 ydot[7] = 1.0*((y[3]*eff_GFP/tau_mRNA_GFP))-1.0*((y[7]*log(2.0)/tau_prot_GFP))+1.0*((60.0*tps_repr-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))));
 	 ydot[8] = (-(log(2.0)/tau_mRNA))*(y[8])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[13]);
 	 ydot[9] = (-(log(2.0)/tau_mRNA))*(y[9])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[11]);
 	 ydot[10] = (-(log(2.0)/tau_mRNA))*(y[10])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[12]);
 	 ydot[11] = (eff/tau_mRNA)*(y[8])+(-(log(2.0)/tau_prot))*(y[11]);
 	 ydot[12] = (eff/tau_mRNA)*(y[9])+(-(log(2.0)/tau_prot))*(y[12]);
 	 ydot[13] = (eff/tau_mRNA)*(y[10])+(-(log(2.0)/tau_prot))*(y[13]);
 	 ydot[14] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[11])+(-(log(2.0)/tau_prot_GFP))*(y[14]);
 	 ydot[15] = (-(log(2.0)/tau_mRNA))*(y[15])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[20]);
 	 ydot[16] = (-(log(2.0)/tau_mRNA))*(y[16])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[18]);
 	 ydot[17] = (-(log(2.0)/tau_mRNA))*(y[17])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[19]);
 	 ydot[18] = (eff/tau_mRNA)*(y[15])+(-(log(2.0)/tau_prot))*(y[18]);
 	 ydot[19] = (eff/tau_mRNA)*(y[16])+(-(log(2.0)/tau_prot))*(y[19]);
 	 ydot[20] = (eff/tau_mRNA)*(y[17])+(-(log(2.0)/tau_prot))*(y[20]);
 	 ydot[21] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[18])+(-(log(2.0)/tau_prot_GFP))*(y[21]);
 	 ydot[22] = (-(log(2.0)/tau_mRNA))*(y[22])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[27]);
 	 ydot[23] = (-(log(2.0)/tau_mRNA))*(y[23])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[25]);
 	 ydot[24] = (-(log(2.0)/tau_mRNA))*(y[24])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[26]);
 	 ydot[25] = (eff/tau_mRNA)*(y[22])+(-(log(2.0)/tau_prot))*(y[25]);
 	 ydot[26] = (eff/tau_mRNA)*(y[23])+(-(log(2.0)/tau_prot))*(y[26]);
 	 ydot[27] = (eff/tau_mRNA)*(y[24])+(-(log(2.0)/tau_prot))*(y[27]);
 	 ydot[28] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[25])+(-(log(2.0)/tau_prot_GFP))*(y[28]);
 	 ydot[29] = (-(log(2.0)/tau_mRNA_GFP))*(y[29]);
 	 ydot[30] = (eff_GFP/tau_mRNA_GFP)*(y[29])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(0.0)+(-(log(2.0)/tau_prot_GFP))*(y[30]);
 	 ydot[31] = (-(log(2.0)/tau_mRNA))*(y[31])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[36]);
 	 ydot[32] = (-(log(2.0)/tau_mRNA))*(y[32])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[34]);
 	 ydot[33] = (-(log(2.0)/tau_mRNA))*(y[33])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[35]);
 	 ydot[34] = (eff/tau_mRNA)*(y[31])+(-(log(2.0)/tau_prot))*(y[34]);
 	 ydot[35] = (eff/tau_mRNA)*(y[32])+(-(log(2.0)/tau_prot))*(y[35]);
 	 ydot[36] = (eff/tau_mRNA)*(y[33])+(-(log(2.0)/tau_prot))*(y[36]);
 	 ydot[37] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[34])+(-(log(2.0)/tau_prot_GFP))*(y[37]);
 	 ydot[38] = (-(log(2.0)/tau_mRNA))*(y[38])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[43]);
 	 ydot[39] = (-(log(2.0)/tau_mRNA))*(y[39])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[41]);
 	 ydot[40] = (-(log(2.0)/tau_mRNA))*(y[40])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[42]);
 	 ydot[41] = (eff/tau_mRNA)*(y[38])+(-(log(2.0)/tau_prot))*(y[41]);
 	 ydot[42] = (eff/tau_mRNA)*(y[39])+(-(log(2.0)/tau_prot))*(y[42]);
 	 ydot[43] = (eff/tau_mRNA)*(y[40])+(-(log(2.0)/tau_prot))*(y[43]);
 	 ydot[44] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[41])+(-(log(2.0)/tau_prot_GFP))*(y[44]);
 	 ydot[45] = (-(log(2.0)/tau_mRNA))*(y[45])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[50]);
 	 ydot[46] = (-(log(2.0)/tau_mRNA))*(y[46])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[48]);
 	 ydot[47] = (-(log(2.0)/tau_mRNA))*(y[47])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[49]);
 	 ydot[48] = (eff/tau_mRNA)*(y[45])+(-(log(2.0)/tau_prot))*(y[48]);
 	 ydot[49] = (eff/tau_mRNA)*(y[46])+(-(log(2.0)/tau_prot))*(y[49]);
 	 ydot[50] = (eff/tau_mRNA)*(y[47])+(-(log(2.0)/tau_prot))*(y[50]);
 	 ydot[51] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[48])+(-(log(2.0)/tau_prot_GFP))*(y[51]);
 	 ydot[52] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(0.0)+(-(log(2.0)/tau_prot_GFP))*(y[52]);
 	 ydot[53] = (-(log(2.0)/tau_mRNA))*(y[53])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[58])+y[0]*log(2.0)/pow(tau_mRNA,2.0);
 	 ydot[54] = (-(log(2.0)/tau_mRNA))*(y[54])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[56])+y[1]*log(2.0)/pow(tau_mRNA,2.0);
 	 ydot[55] = (-(log(2.0)/tau_mRNA))*(y[55])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[57])+y[2]*log(2.0)/pow(tau_mRNA,2.0);
 	 ydot[56] = (eff/tau_mRNA)*(y[53])+(-(log(2.0)/tau_prot))*(y[56])-(y[0]*eff/pow(tau_mRNA,2.0));
 	 ydot[57] = (eff/tau_mRNA)*(y[54])+(-(log(2.0)/tau_prot))*(y[57])-(y[1]*eff/pow(tau_mRNA,2.0));
 	 ydot[58] = (eff/tau_mRNA)*(y[55])+(-(log(2.0)/tau_prot))*(y[58])-(y[2]*eff/pow(tau_mRNA,2.0));
 	 ydot[59] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[56])+(-(log(2.0)/tau_prot_GFP))*(y[59]);
 	 ydot[60] = (-(log(2.0)/tau_mRNA))*(y[60])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[65])+60.0-(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[6],n_Hill)));
 	 ydot[61] = (-(log(2.0)/tau_mRNA))*(y[61])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[63])+60.0-(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[4],n_Hill)));
 	 ydot[62] = (-(log(2.0)/tau_mRNA))*(y[62])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[64])+60.0-(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[5],n_Hill)));
 	 ydot[63] = (eff/tau_mRNA)*(y[60])+(-(log(2.0)/tau_prot))*(y[63]);
 	 ydot[64] = (eff/tau_mRNA)*(y[61])+(-(log(2.0)/tau_prot))*(y[64]);
 	 ydot[65] = (eff/tau_mRNA)*(y[62])+(-(log(2.0)/tau_prot))*(y[65]);
 	 ydot[66] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[63])+(-(log(2.0)/tau_prot_GFP))*(y[66])+60.0-(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[4],n_Hill)));
 	 ydot[67] = (-(log(2.0)/tau_mRNA))*(y[67])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[72])-(pow(KM,(n_Hill-1.0))*n_Hill*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[6],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0));
 	 ydot[68] = (-(log(2.0)/tau_mRNA))*(y[68])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[70])-(pow(KM,(n_Hill-1.0))*n_Hill*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0));
 	 ydot[69] = (-(log(2.0)/tau_mRNA))*(y[69])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[71])-(pow(KM,(n_Hill-1.0))*n_Hill*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[5],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0));
 	 ydot[70] = (eff/tau_mRNA)*(y[67])+(-(log(2.0)/tau_prot))*(y[70]);
 	 ydot[71] = (eff/tau_mRNA)*(y[68])+(-(log(2.0)/tau_prot))*(y[71]);
 	 ydot[72] = (eff/tau_mRNA)*(y[69])+(-(log(2.0)/tau_prot))*(y[72]);
 	 ydot[73] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[70])+(-(log(2.0)/tau_prot_GFP))*(y[73])-(pow(KM,(n_Hill-1.0))*n_Hill*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0));
 	 ydot[74] = (-(log(2.0)/tau_mRNA))*(y[74])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[79])-(pow(KM,n_Hill)*log(KM)*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[6],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,n_Hill)*log(KM)+pow(y[6],n_Hill)*log(y[6]))/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0));
 	 ydot[75] = (-(log(2.0)/tau_mRNA))*(y[75])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[77])-(pow(KM,n_Hill)*log(KM)*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,n_Hill)*log(KM)+pow(y[4],n_Hill)*log(y[4]))/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0));
 	 ydot[76] = (-(log(2.0)/tau_mRNA))*(y[76])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[78])-(pow(KM,n_Hill)*log(KM)*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[5],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,n_Hill)*log(KM)+pow(y[5],n_Hill)*log(y[5]))/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0));
 	 ydot[77] = (eff/tau_mRNA)*(y[74])+(-(log(2.0)/tau_prot))*(y[77]);
 	 ydot[78] = (eff/tau_mRNA)*(y[75])+(-(log(2.0)/tau_prot))*(y[78]);
 	 ydot[79] = (eff/tau_mRNA)*(y[76])+(-(log(2.0)/tau_prot))*(y[79]);
 	 ydot[80] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[77])+(-(log(2.0)/tau_prot_GFP))*(y[80])-(pow(KM,n_Hill)*log(KM)*(60.0*tps_repr-60.0*tps_active)/((pow(KM,n_Hill))+(pow(y[4],n_Hill)))-(pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(KM,n_Hill)*log(KM)+pow(y[4],n_Hill)*log(y[4]))/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0));
 	 ydot[81] = (-(log(2.0)/tau_mRNA))*(y[81])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[86])+(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[6],n_Hill)));
 	 ydot[82] = (-(log(2.0)/tau_mRNA))*(y[82])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[84])+(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[4],n_Hill)));
 	 ydot[83] = (-(log(2.0)/tau_mRNA))*(y[83])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[85])+(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[5],n_Hill)));
 	 ydot[84] = (eff/tau_mRNA)*(y[81])+(-(log(2.0)/tau_prot))*(y[84]);
 	 ydot[85] = (eff/tau_mRNA)*(y[82])+(-(log(2.0)/tau_prot))*(y[85]);
 	 ydot[86] = (eff/tau_mRNA)*(y[83])+(-(log(2.0)/tau_prot))*(y[86]);
 	 ydot[87] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[84])+(-(log(2.0)/tau_prot_GFP))*(y[87])+(pow(KM,n_Hill))*60.0/((pow(KM,n_Hill))+(pow(y[4],n_Hill)));
 	 ydot[88] = (-(log(2.0)/tau_mRNA_GFP))*(y[88])+y[3]*log(2.0)/pow(tau_mRNA_GFP,2.0);
 	 ydot[89] = (eff_GFP/tau_mRNA_GFP)*(y[88])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(0.0)+(-(log(2.0)/tau_prot_GFP))*(y[89])-(y[3]*eff_GFP/pow(tau_mRNA_GFP,2.0));
 	 ydot[90] = (-(log(2.0)/tau_mRNA))*(y[90])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[95]);
 	 ydot[91] = (-(log(2.0)/tau_mRNA))*(y[91])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[93]);
 	 ydot[92] = (-(log(2.0)/tau_mRNA))*(y[92])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[94]);
 	 ydot[93] = (eff/tau_mRNA)*(y[90])+(-(log(2.0)/tau_prot))*(y[93])+y[0]/tau_mRNA;
 	 ydot[94] = (eff/tau_mRNA)*(y[91])+(-(log(2.0)/tau_prot))*(y[94])+y[1]/tau_mRNA;
 	 ydot[95] = (eff/tau_mRNA)*(y[92])+(-(log(2.0)/tau_prot))*(y[95])+y[2]/tau_mRNA;
 	 ydot[96] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[93])+(-(log(2.0)/tau_prot_GFP))*(y[96]);
 	 ydot[97] = (-(log(2.0)/tau_mRNA))*(y[97])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[6],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[6],n_Hill))),2.0))*(y[102]);
 	 ydot[98] = (-(log(2.0)/tau_mRNA))*(y[98])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[100]);
 	 ydot[99] = (-(log(2.0)/tau_mRNA))*(y[99])+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[5],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[5],n_Hill))),2.0))*(y[101]);
 	 ydot[100] = (eff/tau_mRNA)*(y[97])+(-(log(2.0)/tau_prot))*(y[100])+y[4]*log(2.0)/pow(tau_prot,2.0);
 	 ydot[101] = (eff/tau_mRNA)*(y[98])+(-(log(2.0)/tau_prot))*(y[101])+y[5]*log(2.0)/pow(tau_prot,2.0);
 	 ydot[102] = (eff/tau_mRNA)*(y[99])+(-(log(2.0)/tau_prot))*(y[102])+y[6]*log(2.0)/pow(tau_prot,2.0);
 	 ydot[103] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(y[100])+(-(log(2.0)/tau_prot_GFP))*(y[103]);
 	 ydot[104] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(0.0)+(-(log(2.0)/tau_prot_GFP))*(y[104])+y[3]/tau_mRNA_GFP;
 	 ydot[105] = (eff_GFP/tau_mRNA_GFP)*(0.0)+((pow(KM,n_Hill))*(60.0*tps_repr-60.0*tps_active)*(pow(y[4],(n_Hill-1.0))*n_Hill)/pow(((pow(KM,n_Hill))+(pow(y[4],n_Hill))),2.0))*(0.0)+(-(log(2.0)/tau_prot_GFP))*(y[105])+y[7]*log(2.0)/pow(tau_prot_GFP,2.0);

	 for(int i=  0 ; i <  46 ; ++i) RPAR[i] = 0;
}

