/** Code auto-generated by cOde 1.0.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[61];
static double forc[0];
static double cons[0];
static double eventcounter[1];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define inflowp parms[0] 
 #define k00_01 parms[1] 
 #define k01_00 parms[2] 
 #define k00_10 parms[3] 
 #define k10_00 parms[4] 
 #define k01_11 parms[5] 
 #define k11_01 parms[6] 
 #define k01_02 parms[7] 
 #define k02_01 parms[8] 
 #define k10_11 parms[9] 
 #define k11_10 parms[10] 
 #define k10_20 parms[11] 
 #define k20_10 parms[12] 
 #define k11_12 parms[13] 
 #define k12_11 parms[14] 
 #define k11_21 parms[15] 
 #define k21_11 parms[16] 
 #define k02_12 parms[17] 
 #define k12_02 parms[18] 
 #define k02_03 parms[19] 
 #define k03_02 parms[20] 
 #define k20_21 parms[21] 
 #define k21_20 parms[22] 
 #define k20_30 parms[23] 
 #define k30_20 parms[24] 
 #define k12_22 parms[25] 
 #define k22_12 parms[26] 
 #define k12_13 parms[27] 
 #define k13_12 parms[28] 
 #define k21_22 parms[29] 
 #define k22_21 parms[30] 
 #define k21_31 parms[31] 
 #define k31_21 parms[32] 
 #define k03_13 parms[33] 
 #define k13_03 parms[34] 
 #define k30_31 parms[35] 
 #define k31_30 parms[36] 
 #define k22_23 parms[37] 
 #define k23_22 parms[38] 
 #define k22_32 parms[39] 
 #define k32_22 parms[40] 
 #define k13_23 parms[41] 
 #define k23_13 parms[42] 
 #define k31_32 parms[43] 
 #define k32_31 parms[44] 
 #define y0_0 parms[45] 
 #define y1_0 parms[46] 
 #define y2_0 parms[47] 
 #define y3_0 parms[48] 
 #define y4_0 parms[49] 
 #define y5_0 parms[50] 
 #define y6_0 parms[51] 
 #define y7_0 parms[52] 
 #define y8_0 parms[53] 
 #define y9_0 parms[54] 
 #define y10_0 parms[55] 
 #define y11_0 parms[56] 
 #define y12_0 parms[57] 
 #define y13_0 parms[58] 
 #define y14_0 parms[59] 
 #define y15_0 parms[60] 
#define tmin range[0]
#define tmax range[1]


void odemodel_Zheng_PNAS2012_initmod(void (* odeparms)(int *, double *)) {
	 int N=61;
	 odeparms(&N, parms);
	 for(int i=0; i<1; ++i) eventcounter[i] = 0;
}

void odemodel_Zheng_PNAS2012_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_Zheng_PNAS2012_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = 1.0*((inflowp-inflowp*y[15]))-1.0*(y[0]*k00_01)+1.0*(y[1]*k01_00)-1.0*(y[0]*k00_10)+1.0*(y[2]*k10_00)-1.0*(y[0]*(inflowp-inflowp*y[15]));
 	 ydot[1] = 1.0*(y[0]*k00_01)-1.0*(y[1]*k01_00)-1.0*(y[1]*k01_11)+1.0*(y[3]*k11_01)-1.0*(y[1]*k01_02)+1.0*(y[4]*k02_01)-1.0*(y[1]*(inflowp-inflowp*y[15]));
 	 ydot[2] = 1.0*(y[0]*k00_10)-1.0*(y[2]*k10_00)-1.0*(y[2]*k10_11)+1.0*(y[3]*k11_10)-1.0*(y[2]*k10_20)+1.0*(y[5]*k20_10)-1.0*(y[2]*(inflowp-inflowp*y[15]));
 	 ydot[3] = 1.0*(y[2]*k10_11)-1.0*(y[3]*k11_10)+1.0*(y[1]*k01_11)-1.0*(y[3]*k11_01)-1.0*(y[3]*k11_12)+1.0*(y[6]*k12_11)-1.0*(y[3]*k11_21)+1.0*(y[7]*k21_11)-1.0*(y[3]*(inflowp-inflowp*y[15]));
 	 ydot[4] = 1.0*(y[1]*k01_02)-1.0*(y[4]*k02_01)-1.0*(y[4]*k02_12)+1.0*(y[6]*k12_02)-1.0*(y[4]*k02_03)+1.0*(y[8]*k03_02)-1.0*(y[4]*(inflowp-inflowp*y[15]));
 	 ydot[5] = 1.0*(y[2]*k10_20)-1.0*(y[5]*k20_10)-1.0*(y[5]*k20_21)+1.0*(y[7]*k21_20)-1.0*(y[5]*k20_30)+1.0*(y[9]*k30_20)-1.0*(y[5]*(inflowp-inflowp*y[15]));
 	 ydot[6] = 1.0*(y[4]*k02_12)-1.0*(y[6]*k12_02)+1.0*(y[3]*k11_12)-1.0*(y[6]*k12_11)-1.0*(y[6]*k12_22)+1.0*(y[10]*k22_12)-1.0*(y[6]*k12_13)+1.0*(y[14]*k13_12)-1.0*(y[6]*(inflowp-inflowp*y[15]));
 	 ydot[7] = 1.0*(y[5]*k20_21)-1.0*(y[7]*k21_20)+1.0*(y[3]*k11_21)-1.0*(y[7]*k21_11)-1.0*(y[7]*k21_22)+1.0*(y[10]*k22_21)-1.0*(y[7]*k21_31)+1.0*(y[13]*k31_21)-1.0*(y[7]*(inflowp-inflowp*y[15]));
 	 ydot[8] = 1.0*(y[4]*k02_03)-1.0*(y[8]*k03_02)-1.0*(y[8]*k03_13)+1.0*(y[14]*k13_03)-1.0*(y[8]*(inflowp-inflowp*y[15]));
 	 ydot[9] = 1.0*(y[5]*k20_30)-1.0*(y[9]*k30_20)-1.0*(y[9]*k30_31)+1.0*(y[13]*k31_30)-1.0*(y[9]*(inflowp-inflowp*y[15]));
 	 ydot[10] = 1.0*(y[6]*k12_22)-1.0*(y[10]*k22_12)+1.0*(y[7]*k21_22)-1.0*(y[10]*k22_21)-1.0*(y[10]*k22_23)+1.0*(y[11]*k23_22)-1.0*(y[10]*k22_32)+1.0*(y[12]*k32_22)-1.0*(y[10]*(inflowp-inflowp*y[15]));
 	 ydot[11] = 1.0*(y[10]*k22_23)-1.0*(y[11]*k23_22)+1.0*(y[14]*k13_23)-1.0*(y[11]*k23_13)-1.0*(y[11]*(inflowp-inflowp*y[15]));
 	 ydot[12] = 1.0*(y[10]*k22_32)-1.0*(y[12]*k32_22)+1.0*(y[13]*k31_32)-1.0*(y[12]*k32_31)-1.0*(y[12]*(inflowp-inflowp*y[15]));
 	 ydot[13] = 1.0*(y[9]*k30_31)-1.0*(y[13]*k31_30)+1.0*(y[7]*k21_31)-1.0*(y[13]*k31_21)-1.0*(y[13]*k31_32)+1.0*(y[12]*k32_31)-1.0*(y[13]*(inflowp-inflowp*y[15]));
 	 ydot[14] = 1.0*(y[8]*k03_13)-1.0*(y[14]*k13_03)+1.0*(y[6]*k12_13)-1.0*(y[14]*k13_12)-1.0*(y[14]*k13_23)+1.0*(y[11]*k23_13)-1.0*(y[14]*(inflowp-inflowp*y[15]));
 	 ydot[15] = 1.0*(0.0);

}

/** Event function **/
void odemodel_Zheng_PNAS2012_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 0 & eventcounter[0] == 0) {
		y[15] = 0;
		y[15] = 1.0;
		eventcounter[0] = eventcounter[0] + 1.;
	 }


}
